### ISSUE TITLE
git clone repo failing - filename too long

### ISSUE THREAD

**Issue by lbesnard** [aodn/python-aodndata#218]
I don't know why it doesn't work anymore, but I can't clone the repo anymore(edit: I can clone it, but not the failing files), due to filename being too long.

Apparently due to the home folder being in an encrypted partition on linux (see https://github.com/szabgab/codeandtalk.com/issues/170), which I'm not going to change now.. Has it happened to anyone else? Could we just rename those files or something?

```
/usr/bin/git clone git@github.com:aodn/python-aodndata.git
Cloning into 'python-aodndata'...
remote: Enumerating objects: 406, done.
remote: Counting objects: 100% (406/406), done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 3961 (delta 283), reused 312 (delta 215), pack-reused 3555
Receiving objects: 100% (3961/3961), 176.03 MiB | 4.09 MiB/s, done.
Resolving deltas: 100% (2558/2558), done.
error: unable to create file test_aodndata/moorings/IMOS_ANMN-NRS_AETVZ_20181213T080000Z_NRSROT-ADCP_FV01_NRSROT-ADCP-1812-Sentinel-or-Monitor-Workhorse-ADCP-44_END-20181215T100000Z_C-20200430T000000Z.nc: File name too long
error: unable to create file test_aodndata/moorings/IMOS_ANMN-NRS_AETVZ_20191016T080000Z_NRSROT-ADCP_FV01_NRSROT-ADCP-1910-Sentinel-or-Monitor-Workhorse-ADCP-44_END-20191018T100000Z_C-20200430T000000Z.nc: File name too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by lwgordonimos** [comment]
If they are legitimate file names, both in terms of being well under the 255 byte limit and also in terms of the IMOS naming convention, then the bug would appear to be with your weird home directory setup!

**Comment by lbesnard** [comment]
(edit: I can clone it, but not the failing files)

**Comment by lbesnard** [comment]
@lwgordonimos yeah I'm trying to understand, but I'm using /usr/bin/git

**Comment by lbesnard** [comment]
yeah after looking more into it, it's due to having a home dir encrypted...
https://bugs.launchpad.net/ecryptfs/+bug/344878
fun...

**Comment by lwgordonimos** [comment]
I don't have a good suggestion unfortunately. I just use the whole of disk "Encrypted LVM" option, which is much more transparent and just presents as normal ext4. I haven't used the eCryptfs method, but I like the simplicity of the "dm-crypt" method for my workstation, and I don't need any of the purported benefits of eCryptfs like portability or different encryption keys for different files. I just want the disk to be random garbage unless I enter a passphrase when it boots, so if it gets stolen it can't just be plugged into a USB cradle and mounted.

This has a pretty good comparison of the two: https://stackoverflow.com/a/18234635

1. Migrate yourself away from eCryptfs
1. Confirm whether these long file names are legitimate (question for @mhidas I would suggest, on both the specific files and on the filename convention stuff too perhaps)

**Comment by mhidas** [comment]
> Confirm whether these long file names are legitimate

Yep, perfectly legitimate. Such is the nature of our file naming convention, combined with the wonderful complexity of the moorings data.

@lbesnard What's changed? I assume you've checked out this repo before - how come it worked so far? 
Could you just check it out on another file system that isn't encrypted?

**Comment by lbesnard** [comment]
> @lbesnard What's changed? I assume you've checked out this repo before - how come it worked so far?

yeah what has changed was reinstalling my computer last week after some of the trouble I had. When I re-installed mint, I selected the "encrypt the home folder" option. Should have known better.


>  Could you just check it out on another file system that isn't encrypted?

pretty much have to reinstall everything as I would need a different partition. I will have to do this ...

> I just use the whole of disk "Encrypted LVM" option, which is much more transparent and just presents as normal ext4.

yeah absolutely that's what I've read.

thanks for your time

I'll close the issue as the issue is me :(
