### ISSUE TITLE
SRS ALTIMETRY pre-deployment handler review

### ISSUE THREAD

**Issue by ghost** [aodn/python-aodndata#23]
https://github.com/aodn/python-aodndata/blob/e2a6cc6e3e7dad1c32727c5bd6c8c00255f9e7ec/aodndata/srs/srs_altimetry.py#L14
I find this to be a cleaner pattern for opening/closing the file and retriving a couple of values. Let the context manager handle the opening/closing:

```python
with Dataset(filepath, mode='r') as n:
    site_code = n.site_code
    instrument = n.instrument
```

https://github.com/aodn/python-aodndata/blob/e2a6cc6e3e7dad1c32727c5bd6c8c00255f9e7ec/aodndata/srs/srs_altimetry.py#L26

It would be nicer on the handler if when you *know* that a path can't be determined, it throws an exception to that effect.

For example, instead of returning None, replace the return statement with something like:
```python
raise ValueError("unknown instrument '{instrument}'".format(instrument=instrument)
```

This avoids the scenario where this returns None, and then something tries to use it like a path and it becomes a confusing TypeError later on.

**Comment by lbesnard** [comment]
@lwgordonimos added this to the commit
