### ISSUE TITLE
SSTAARS missing files in current pipeline

### ISSUE THREAD

**Issue by ggalibert** [aodn/python-aodndata#83]
The following files are currently not handled by the SSTAARS pipeline:
- SSTAARS.nc
- SSTAARS_daily_fit.nc

Both don't need to be harvested, but just pushed to S3 to the following location, respectively:
- CSIRO/Climatology/SSTAARS/2017/SSTAARS.nc
- CSIRO/Climatology/SSTAARS/2017/AODN-product/SSTAARS_daily_fit.nc

**Comment by lbesnard** [comment]
https://github.com/aodn/python-aodndata/pull/84#issuecomment-420160501
